// AUTO-GENERATED from Gábor pigment email (validated by Norbert)
// Efectto PU — pigment receptek
// Mértékegység: g pigment / 1 kg kész mikrocement
// 48 szín × 10 pigment opció × 3 szemcseméret

export type EfecttoPigmentRecipe = {
  amarillo?: number;
  negro?: number;
  rojoNaranja?: number;
  rojoIntenso?: number;
  blanco?: number;
  azul?: number;
  verde?: number;
  negroHumo?: number;
  amarilloVainilla?: number;
  amarilloLimon?: number;
};

export const EFECTTO_PIGMENT_LABELS: Record<keyof EfecttoPigmentRecipe, string> = {
  amarillo: 'Amarillo',
  negro: 'Negro',
  rojoNaranja: 'Rojo Naranja',
  rojoIntenso: 'Rojo Intenso',
  blanco: 'Blanco',
  azul: 'Azul',
  verde: 'Verde',
  negroHumo: 'Negro Humo',
  amarilloVainilla: 'Amarillo Vainilla',
  amarilloLimon: 'Amarillo Limon',
};

export const EFECTTO_PU_COLORS = [
  'BLANCO',
  'BLANCO ROTO',
  'BONE',
  'SHALE GREY',
  'SPIKE',
  'LIQUEN',
  'MOJAVE',
  'PORCELAIN',
  'UNIVERSE',
  'MOSS',
  'BREEZE',
  'INDIA',
  'BLUSH',
  'CORAL',
  'PAPYRUS',
  'CHAMPAGNE',
  'WASABI',
  'KHAKI',
  'SALMON',
  'CAFÉ',
  'SÁHARA',
  'JADE',
  'CEMENTO',
  'GINGER',
  'RAFFIA',
  'CAIRO',
  'CLAY',
  'MARRÓN',
  'COBRE',
  'SAND',
  'CALABAZA',
  'PINK',
  'EUCALYPTUS',
  'HIMALAYA',
  'PEARL GREY',
  'PIZARRA',
  'PURE BLACK',
  'MOON',
  'ACERO',
  'AZUL PROFUNDO',
  'ADRA',
  'SAMOS',
  'PLOMO',
  'KALAHARI',
  'DESERT TAN',
  'COTTON',
  'NÉBULA',
  'PERLA',
] as const;

export type EFECTTO_PUColorName = typeof EFECTTO_PU_COLORS[number];

export type EFECTTO_PUGrainSize = 'small' | 'medium' | 'big';

export const EFECTTO_PU_GRAIN_LABELS: Record<EFECTTO_PUGrainSize, string> = {
  small: 'Small Grain',
  medium: 'Medium Grain',
  big: 'Big Grain',
};

export const EFECTTO_PU_RECIPES: Record<EFECTTO_PUGrainSize, Record<EFECTTO_PUColorName, EfecttoPigmentRecipe>> = {
  small: {
    'BLANCO': { blanco: 80 },
    'BLANCO ROTO': { amarillo: 0.18, rojoNaranja: 0.005, blanco: 30 },
    'BONE': { amarillo: 0.1, negro: 0.09, blanco: 3 },
    'SHALE GREY': { negro: 2, azul: 0.4 },
    'SPIKE': { amarillo: 0.07, negro: 0.15, rojoNaranja: 0.05, blanco: 3 },
    'LIQUEN': { amarillo: 0.3, negro: 0.3, blanco: 20.4, verde: 0.5 },
    'MOJAVE': { amarillo: 0.5, negro: 0.2, rojoNaranja: 0.07, blanco: 2.9 },
    'PORCELAIN': { blanco: 18, amarilloVainilla: 0.2, amarilloLimon: 0.2 },
    'UNIVERSE': { negro: 0.3, blanco: 1.3 },
    'MOSS': { amarillo: 1, blanco: 45, azul: 1.5 },
    'BREEZE': { amarillo: 0.4, blanco: 10, azul: 2.5 },
    'INDIA': { amarillo: 3, negro: 0.35, blanco: 30 },
    'BLUSH': { amarillo: 0.3, rojoIntenso: 0.05, blanco: 15, azul: 0.15 },
    'CORAL': { rojoNaranja: 1.2 },
    'PAPYRUS': { amarillo: 0.47, negro: 0.5, rojoNaranja: 0.25, blanco: 10, azul: 1 },
    'CHAMPAGNE': { amarillo: 0.5, negro: 0.2, rojoNaranja: 0.08, blanco: 10.5 },
    'WASABI': { amarillo: 4, blanco: 46, verde: 3 },
    'KHAKI': { amarillo: 1.6, negro: 0.35, rojoNaranja: 0.35, blanco: 16, verde: 2.1 },
    'SALMON': { amarillo: 4.2, negro: 0.1, rojoNaranja: 1.4, blanco: 40 },
    'CAFÉ': { amarillo: 1.8, negro: 0.6, rojoNaranja: 1.5, blanco: 10 },
    'SÁHARA': { amarillo: 1.5, negro: 0.37, rojoNaranja: 0.7, blanco: 37 },
    'JADE': { blanco: 12, azul: 6, amarilloVainilla: 11.3 },
    'CEMENTO': { negro: 0.35, verde: 0.2 },
    'GINGER': { amarillo: 1.8, negro: 0.03, rojoNaranja: 0.1, blanco: 2 },
    'RAFFIA': { amarillo: 1, negro: 1, rojoNaranja: 0.4, blanco: 15 },
    'CAIRO': { amarillo: 0.1, negro: 0.07, rojoNaranja: 0.05, blanco: 1.0 },
    'CLAY': { amarillo: 0.8, negro: 0.4, rojoNaranja: 0.8, blanco: 18.5 },
    'MARRÓN': { negro: 1.9, rojoNaranja: 0.9 },
    'COBRE': { amarillo: 1.5, negro: 1, rojoNaranja: 2.5 },
    'SAND': { amarillo: 1, negro: 0.6, rojoNaranja: 0.1, blanco: 6 },
    'CALABAZA': { amarillo: 14.5, negro: 0.05, rojoNaranja: 5, blanco: 4 },
    'PINK': { amarillo: 0.25, rojoIntenso: 0.12, blanco: 13, azul: 0.2 },
    'EUCALYPTUS': { amarillo: 0.2, blanco: 14, azul: 2, amarilloVainilla: 9 },
    'HIMALAYA': { negro: 1.3, azul: 0.2 },
    'PEARL GREY': { amarillo: 0.15, negro: 0.4, rojoNaranja: 0.05, blanco: 5 },
    'PIZARRA': { negro: 3 },
    'PURE BLACK': { negroHumo: 2 },
    'MOON': { amarillo: 0.8, negro: 4, blanco: 38 },
    'ACERO': { amarillo: 0.05, negro: 0.8, rojoNaranja: 0.05, blanco: 5 },
    'AZUL PROFUNDO': { negro: 0.4, blanco: 3, azul: 5, verde: 0.5 },
    'ADRA': { amarillo: 0.5, negro: 0.6, rojoNaranja: 0.1 },
    'SAMOS': { amarillo: 0.5, negro: 0.8, rojoNaranja: 0.5, blanco: 2.5 },
    'PLOMO': { amarillo: 0.8, negro: 4, rojoNaranja: 1.2, blanco: 5 },
    'KALAHARI': { amarillo: 1.1, negro: 0.2, rojoNaranja: 0.32, blanco: 0.5 },
    'DESERT TAN': { amarillo: 1.9, negro: 0.55, rojoNaranja: 0.3, blanco: 5.6 },
    'COTTON': { amarillo: 0.4, negro: 0.1, rojoNaranja: 0.08, blanco: 20 },
    'NÉBULA': { amarillo: 0.2, blanco: 23 },
    'PERLA': { blanco: 7, azul: 0.15 },
  },
  medium: {
    'BLANCO': { blanco: 80 },
    'BLANCO ROTO': { amarillo: 0.1, rojoNaranja: 0.005 },
    'BONE': { amarillo: 0.33, blanco: 7 },
    'SHALE GREY': { negro: 1.7, blanco: 1.35, azul: 0.7 },
    'SPIKE': { amarillo: 0.15, negro: 0.09, rojoNaranja: 0.1, blanco: 7 },
    'LIQUEN': { amarillo: 0.3, negro: 0.25, blanco: 21.6, verde: 0.5 },
    'MOJAVE': { amarillo: 1.5, negro: 0.05, rojoNaranja: 0.15, blanco: 9 },
    'PORCELAIN': { amarillo: 0.4, blanco: 21.6, amarilloLimon: 0.15 },
    'UNIVERSE': { amarillo: 0.5, negro: 0.7, blanco: 17.1 },
    'MOSS': { amarillo: 1, blanco: 45, azul: 1.1 },
    'BREEZE': { amarillo: 0.25, blanco: 16.2, azul: 2.8 },
    'INDIA': { amarillo: 4, negro: 0.2, blanco: 25.2 },
    'BLUSH': { amarillo: 0.35, rojoIntenso: 0.06, blanco: 25.2, azul: 0.1 },
    'CORAL': { rojoNaranja: 2.4, blanco: 6.7, amarilloLimon: 1 },
    'PAPYRUS': { amarillo: 0.6, negro: 0.3, rojoNaranja: 0.3, blanco: 12.6, verde: 1 },
    'CHAMPAGNE': { amarillo: 1.5, negro: 0.1, rojoNaranja: 0.08, blanco: 18 },
    'WASABI': { amarillo: 4, blanco: 45, verde: 2.45 },
    'KHAKI': { amarillo: 2, negro: 0.3, rojoNaranja: 0.25, blanco: 24.3, verde: 2 },
    'SALMON': { amarillo: 7, negro: 0.05, rojoNaranja: 1.95, blanco: 4 },
    'CAFÉ': { amarillo: 3.1, negro: 0.5, rojoNaranja: 2, blanco: 13.5 },
    'SÁHARA': { amarillo: 2.5, negro: 0.3, rojoNaranja: 1.2, blanco: 37.8 },
    'JADE': { blanco: 11.2, azul: 5.5, amarilloVainilla: 14 },
    'CEMENTO': { negro: 0.35, blanco: 6, verde: 0.25 },
    'GINGER': { amarillo: 11, rojoNaranja: 0.13, blanco: 21.6 },
    'RAFFIA': { amarillo: 1.2, negro: 0.8, rojoNaranja: 0.5, blanco: 15.3 },
    'CAIRO': { amarillo: 0.5, negro: 0.05, rojoNaranja: 0.1, blanco: 7.5 },
    'CLAY': { amarillo: 0.7, negro: 0.1, rojoNaranja: 0.8, blanco: 13.5 },
    'MARRÓN': { amarillo: 0.25, negro: 1.16, rojoNaranja: 0.94 },
    'COBRE': { amarillo: 2.8, negro: 0.6, rojoNaranja: 3.2 },
    'SAND': { amarillo: 1.2, negro: 0.2, rojoNaranja: 0.08, blanco: 9 },
    'CALABAZA': { amarillo: 11, rojoNaranja: 5, blanco: 7.1 },
    'PINK': { amarillo: 0.25, rojoIntenso: 0.15, blanco: 18, azul: 0.05 },
    'EUCALYPTUS': { blanco: 29.7, azul: 1.8, amarilloVainilla: 10 },
    'HIMALAYA': { negro: 0.96, blanco: 0.9, azul: 0.04 },
    'PEARL GREY': { amarillo: 0.1, negro: 0.2, rojoNaranja: 0.03, blanco: 9 },
    'PIZARRA': { negro: 2.5 },
    'PURE BLACK': { negroHumo: 2 },
    'MOON': { amarillo: 0.5, negro: 4, blanco: 31.5 },
    'ACERO': { amarillo: 0.1, negro: 0.8, rojoNaranja: 0.15, blanco: 3 },
    'AZUL PROFUNDO': { blanco: 4.5, azul: 4, verde: 0.1 },
    'ADRA': { amarillo: 0.15, negro: 0.25, rojoNaranja: 0.05 },
    'SAMOS': { amarillo: 0.67, negro: 0.45, rojoNaranja: 0.33 },
    'PLOMO': { amarillo: 0.1, negro: 1.2, rojoNaranja: 0.3 },
    'KALAHARI': { amarillo: 2, negro: 0.03, rojoNaranja: 0.3, blanco: 2.5 },
    'DESERT TAN': { amarillo: 2.3, negro: 0.33, rojoNaranja: 0.3, blanco: 7.9 },
    'COTTON': { amarillo: 0.7, negro: 0.1, rojoNaranja: 0.05, blanco: 45 },
    'NÉBULA': { amarillo: 0.22, blanco: 43.2 },
    'PERLA': { blanco: 11, azul: 0.13 },
  },
  big: {
    'BLANCO': { blanco: 80 },
    'BLANCO ROTO': { amarillo: 0.1, rojoNaranja: 0.005, blanco: 30 },
    'BONE': { amarillo: 0.33, blanco: 9 },
    'SHALE GREY': { negro: 1.7, blanco: 1.5, azul: 0.7 },
    'SPIKE': { amarillo: 0.15, negro: 0.09, rojoNaranja: 0.1, blanco: 7 },
    'LIQUEN': { amarillo: 0.3, negro: 0.25, blanco: 30, verde: 0.5 },
    'MOJAVE': { amarillo: 1.5, negro: 0.05, rojoNaranja: 0.15, blanco: 10 },
    'PORCELAIN': { amarillo: 0.4, blanco: 30, amarilloLimon: 0.15 },
    'UNIVERSE': { amarillo: 0.5, negro: 0.7, blanco: 19 },
    'MOSS': { amarillo: 1, blanco: 64, azul: 1.1 },
    'BREEZE': { amarillo: 0.25, blanco: 18, azul: 2.8 },
    'INDIA': { amarillo: 4, negro: 0.2, blanco: 35 },
    'BLUSH': { amarillo: 0.35, rojoIntenso: 0.06, blanco: 35, azul: 0.1 },
    'CORAL': { rojoNaranja: 2.4, blanco: 6.7, amarilloLimon: 1 },
    'PAPYRUS': { amarillo: 0.6, negro: 0.3, rojoNaranja: 0.3, blanco: 14, verde: 1 },
    'CHAMPAGNE': { amarillo: 1.5, negro: 0.1, rojoNaranja: 0.08, blanco: 20 },
    'WASABI': { amarillo: 4, blanco: 50, verde: 2.45 },
    'KHAKI': { amarillo: 2, negro: 0.3, rojoNaranja: 0.25, blanco: 27, verde: 2 },
    'SALMON': { amarillo: 7, negro: 0.05, rojoNaranja: 1.95, blanco: 4 },
    'CAFÉ': { amarillo: 3.1, negro: 0.5, rojoNaranja: 2, blanco: 15 },
    'SÁHARA': { amarillo: 2.5, negro: 0.3, rojoNaranja: 1.2, blanco: 42 },
    'JADE': { blanco: 12.4, azul: 5.5, amarilloVainilla: 14 },
    'CEMENTO': { negro: 0.35, blanco: 6, verde: 0.25 },
    'GINGER': { amarillo: 11, rojoNaranja: 0.13, blanco: 24 },
    'RAFFIA': { amarillo: 1.2, negro: 0.8, rojoNaranja: 0.5, blanco: 17 },
    'CAIRO': { amarillo: 0.5, negro: 0.05, rojoNaranja: 0.1, blanco: 7.5 },
    'CLAY': { amarillo: 0.7, negro: 0.1, rojoNaranja: 0.8, blanco: 15 },
    'MARRÓN': { amarillo: 0.25, negro: 1.16, rojoNaranja: 0.94 },
    'COBRE': { amarillo: 2.8, negro: 0.6, rojoNaranja: 3.2 },
    'SAND': { amarillo: 1.2, negro: 0.2, rojoNaranja: 0.08, blanco: 10 },
    'CALABAZA': { amarillo: 11, rojoNaranja: 5, blanco: 7.1 },
    'PINK': { amarillo: 0.25, rojoIntenso: 0.15, blanco: 20, azul: 0.05 },
    'EUCALYPTUS': { blanco: 33, azul: 1.8, amarilloVainilla: 10 },
    'HIMALAYA': { negro: 0.96, blanco: 0.9, azul: 0.04 },
    'PEARL GREY': { amarillo: 0.1, negro: 0.2, rojoNaranja: 0.03, blanco: 10 },
    'PIZARRA': { negro: 2.5 },
    'PURE BLACK': { negroHumo: 2 },
    'MOON': { amarillo: 0.5, negro: 4, blanco: 35 },
    'ACERO': { amarillo: 0.1, negro: 0.8, rojoNaranja: 0.15, blanco: 3 },
    'AZUL PROFUNDO': { blanco: 4.5, azul: 4, verde: 0.1 },
    'ADRA': { amarillo: 0.15, negro: 0.25, rojoNaranja: 0.05 },
    'SAMOS': { amarillo: 0.67, negro: 0.45, rojoNaranja: 0.33 },
    'PLOMO': { amarillo: 0.1, negro: 1.2, rojoNaranja: 0.3 },
    'KALAHARI': { amarillo: 2, negro: 0.03, rojoNaranja: 0.3, blanco: 2.5 },
    'DESERT TAN': { amarillo: 2.3, negro: 0.33, rojoNaranja: 0.3, blanco: 8.8 },
    'COTTON': { amarillo: 0.7, negro: 0.1, rojoNaranja: 0.05, blanco: 50 },
    'NÉBULA': { amarillo: 0.22, blanco: 48 },
    'PERLA': { blanco: 14, azul: 0.13 },
  },
};
