// AUTO-GENERATED from Gábor pigment email (validated by Norbert)
// Efectto Quartz — pigment receptek
// Mértékegység: g pigment / 1 kg kész mikrocement
// 48 szín × 10 pigment opció × 3 szemcseméret

export type EfecttoPigmentRecipe = {
  amarillo?: number;
  negro?: number;
  rojoNaranja?: number;
  rojoIntenso?: number;
  blanco?: number;
  azul?: number;
  verde?: number;
  negroHumo?: number;
  amarilloVainilla?: number;
  amarilloLimon?: number;
};

export const EFECTTO_PIGMENT_LABELS: Record<keyof EfecttoPigmentRecipe, string> = {
  amarillo: 'Amarillo',
  negro: 'Negro',
  rojoNaranja: 'Rojo Naranja',
  rojoIntenso: 'Rojo Intenso',
  blanco: 'Blanco',
  azul: 'Azul',
  verde: 'Verde',
  negroHumo: 'Negro Humo',
  amarilloVainilla: 'Amarillo Vainilla',
  amarilloLimon: 'Amarillo Limon',
};

export const EFECTTO_QUARTZ_COLORS = [
  'BLANCO',
  'BLANCO ROTO',
  'BONE',
  'SHALE GREY',
  'SPIKE',
  'LIQUEN',
  'MOJAVE',
  'PORCELAIN',
  'UNIVERSE',
  'MOSS',
  'BREEZE',
  'INDIA',
  'BLUSH',
  'CORAL',
  'PAPYRUS',
  'CHAMPAGNE',
  'WASABI',
  'KHAKI',
  'SALMON',
  'CAFÉ',
  'SÁHARA',
  'JADE',
  'CEMENTO',
  'GINGER',
  'RAFFIA',
  'CAIRO',
  'CLAY',
  'MARRÓN',
  'COBRE',
  'SAND',
  'CALABAZA',
  'PINK',
  'EUCALYPTUS',
  'HIMALAYA',
  'PEARL GREY',
  'PIZARRA',
  'PURE BLACK',
  'MOON',
  'ACERO',
  'AZUL PROFUNDO',
  'ADRA',
  'SAMOS',
  'PLOMO',
  'KALAHARI',
  'DESERT TAN',
  'COTTON',
  'NÉBULA',
  'PERLA',
] as const;

export type EFECTTO_QUARTZColorName = typeof EFECTTO_QUARTZ_COLORS[number];

export type EFECTTO_QUARTZGrainSize = 'small' | 'medium' | 'big';

export const EFECTTO_QUARTZ_GRAIN_LABELS: Record<EFECTTO_QUARTZGrainSize, string> = {
  small: 'Small Grain',
  medium: 'Medium Grain',
  big: 'Big Grain',
};

export const EFECTTO_QUARTZ_RECIPES: Record<EFECTTO_QUARTZGrainSize, Record<EFECTTO_QUARTZColorName, EfecttoPigmentRecipe>> = {
  small: {
    'BLANCO': { blanco: 100 },
    'BLANCO ROTO': { amarillo: 0.18, negro: 0.08, rojoNaranja: 0.005, blanco: 30 },
    'BONE': { amarillo: 0.16, negro: 0.15, rojoNaranja: 0.01, blanco: 1.9 },
    'SHALE GREY': { negro: 2.2, azul: 0.4 },
    'SPIKE': { amarillo: 0.1, negro: 0.26, rojoNaranja: 0.07 },
    'LIQUEN': { amarillo: 0.55, negro: 0.5, blanco: 18, verde: 0.5 },
    'MOJAVE': { amarillo: 0.9, negro: 0.22, rojoNaranja: 0.12, blanco: 2.4 },
    'PORCELAIN': { blanco: 5, amarilloVainilla: 0.2, amarilloLimon: 0.2 },
    'UNIVERSE': { negro: 0.49, blanco: 1 },
    'MOSS': { amarillo: 1, blanco: 34, azul: 1.5 },
    'BREEZE': { amarillo: 0.4, blanco: 10, azul: 2.8 },
    'INDIA': { amarillo: 3, negro: 0.4, blanco: 30 },
    'BLUSH': { amarillo: 0.3, rojoIntenso: 0.05, blanco: 15, azul: 0.15 },
    'CORAL': { rojoNaranja: 1.2 },
    'PAPYRUS': { amarillo: 0.47, negro: 0.9, rojoNaranja: 0.25, blanco: 10, verde: 1.1 },
    'CHAMPAGNE': { amarillo: 0.8, negro: 0.4, rojoNaranja: 0.1, blanco: 10.3 },
    'WASABI': { amarillo: 4.1, blanco: 46.5, verde: 3.1 },
    'KHAKI': { amarillo: 1.5, negro: 0.5, rojoNaranja: 0.3, blanco: 16, verde: 2.3 },
    'SALMON': { amarillo: 5.9, negro: 0.25, rojoNaranja: 2, blanco: 33.8 },
    'CAFÉ': { amarillo: 2.5, negro: 1.3, rojoNaranja: 1.5, blanco: 10 },
    'SÁHARA': { amarillo: 1.73, negro: 0.61, rojoNaranja: 0.95, blanco: 27.2 },
    'JADE': { blanco: 4, azul: 10, amarilloVainilla: 17.7 },
    'CEMENTO': { negro: 0.44, verde: 0.22 },
    'GINGER': { amarillo: 1.9, negro: 0.07, rojoNaranja: 0.13, blanco: 2 },
    'RAFFIA': { amarillo: 1.5, negro: 1.4, rojoNaranja: 0.5, blanco: 13 },
    'CAIRO': { amarillo: 0.4, negro: 0.11, rojoNaranja: 0.13, blanco: 0.9 },
    'CLAY': { amarillo: 0.8, negro: 0.44, rojoNaranja: 0.8, blanco: 10.7 },
    'MARRÓN': { negro: 2.66, rojoNaranja: 1.35 },
    'COBRE': { amarillo: 2, negro: 1.5, rojoNaranja: 3 },
    'SAND': { amarillo: 1, negro: 0.6, rojoNaranja: 0.08, blanco: 5.2 },
    'CALABAZA': { amarillo: 14.66, negro: 0.08, rojoNaranja: 5.3, blanco: 0.7 },
    'PINK': { amarillo: 0.3, rojoIntenso: 0.1, blanco: 11.2, azul: 0.25 },
    'EUCALYPTUS': { amarillo: 0.2, blanco: 1, azul: 2.1, amarilloLimon: 9 },
    'HIMALAYA': { negro: 1.5, azul: 0.2 },
    'PEARL GREY': { amarillo: 0.15, negro: 0.45, rojoNaranja: 0.05, blanco: 2 },
    'PIZARRA': { negro: 5 },
    'PURE BLACK': { negroHumo: 3 },
    'MOON': { amarillo: 0.8, negro: 5, blanco: 32 },
    'ACERO': { amarillo: 0.1, negro: 1.2, rojoNaranja: 0.05, blanco: 3 },
    'AZUL PROFUNDO': { negro: 0.6, blanco: 3, azul: 6, verde: 0.6 },
    'ADRA': { amarillo: 0.4, negro: 0.5, rojoNaranja: 0.1 },
    'SAMOS': { amarillo: 1.16, negro: 2.1, rojoNaranja: 0.9 },
    'PLOMO': { amarillo: 0.8, negro: 5, rojoNaranja: 1.2, blanco: 2.9 },
    'KALAHARI': { amarillo: 0.66, negro: 0.06, rojoNaranja: 0.08, blanco: 0.84 },
    'DESERT TAN': { amarillo: 1.6, negro: 0.65, rojoNaranja: 0.3, blanco: 3 },
    'COTTON': { amarillo: 0.6, negro: 0.2, rojoNaranja: 0.1, blanco: 20 },
    'NÉBULA': { amarillo: 0.25, negro: 0.07, blanco: 25 },
    'PERLA': { negro: 0.17 },
  },
  medium: {
    'BLANCO': { blanco: 70 },
    'BLANCO ROTO': { amarillo: 0.18, negro: 0.08, rojoNaranja: 0.005, blanco: 36 },
    'BONE': { amarillo: 0.18, blanco: 7 },
    'SHALE GREY': { negro: 1.5, azul: 0.8 },
    'SPIKE': { rojoIntenso: 0.07, blanco: 4 },
    'LIQUEN': { amarillo: 0.06, negro: 0.13, blanco: 20, verde: 0.33 },
    'MOJAVE': { amarillo: 0.6, rojoNaranja: 0.1, blanco: 3.0 },
    'PORCELAIN': { blanco: 20, verde: 0.06, amarilloVainilla: 0.4, amarilloLimon: 0.4 },
    'UNIVERSE': { amarillo: 0.2, negro: 0.63, blanco: 7 },
    'MOSS': { blanco: 44, azul: 1.5, amarilloVainilla: 4.5 },
    'BREEZE': { amarillo: 0.25, blanco: 27.4, azul: 3.8, verde: 0.8 },
    'INDIA': { amarillo: 4.5, negro: 0.25, blanco: 47 },
    'BLUSH': { amarillo: 0.2, rojoIntenso: 0.05, blanco: 21, azul: 0.07 },
    'CORAL': { amarillo: 6, rojoNaranja: 11, blanco: 41 },
    'PAPYRUS': { amarillo: 0.95, negro: 1.33, blanco: 13 },
    'CHAMPAGNE': { amarillo: 1.6, negro: 0.4, blanco: 30 },
    'WASABI': { amarillo: 4.5, blanco: 30, verde: 2.8 },
    'KHAKI': { amarillo: 1, negro: 0.4, blanco: 18, verde: 2.6 },
    'SALMON': { amarillo: 5, negro: 0.08, rojoNaranja: 1.7, blanco: 32 },
    'CAFÉ': { amarillo: 6.6, negro: 2, rojoNaranja: 3.7, blanco: 27 },
    'SÁHARA': { amarillo: 2.9, negro: 0.6, rojoNaranja: 1.0, blanco: 40 },
    'JADE': { blanco: 7.0, azul: 6.6, amarilloVainilla: 13 },
    'CEMENTO': { negro: 0.5, blanco: 3.0, verde: 0.43 },
    'GINGER': { amarillo: 7.7, rojoNaranja: 0.13, blanco: 14 },
    'RAFFIA': { amarillo: 1.2, negro: 1.0, rojoNaranja: 0.5, blanco: 13 },
    'CAIRO': { amarillo: 0.15, negro: 0.04, rojoNaranja: 0.07, blanco: 0.5 },
    'CLAY': { amarillo: 2.3, negro: 0.18, rojoNaranja: 1.2, blanco: 12 },
    'MARRÓN': { amarillo: 0.36, negro: 1.6, rojoNaranja: 1 },
    'COBRE': { amarillo: 2.3, negro: 0.77, rojoNaranja: 3 },
    'SAND': { amarillo: 1.0, negro: 0.25, rojoNaranja: 0.06, blanco: 6 },
    'CALABAZA': { amarillo: 11, rojoNaranja: 4.1, blanco: 4 },
    'PINK': { amarillo: 0.25, rojoIntenso: 0.15, blanco: 17, azul: 0.1 },
    'EUCALYPTUS': { blanco: 24, azul: 1.8, amarilloVainilla: 10 },
    'HIMALAYA': { negro: 1.2, blanco: 0.3, azul: 0.07 },
    'PEARL GREY': { amarillo: 0.08, negro: 0.22, rojoNaranja: 0.03, blanco: 4.0 },
    'PIZARRA': { negro: 4 },
    'PURE BLACK': { negroHumo: 2.5 },
    'MOON': { amarillo: 0.6, negro: 5, blanco: 33 },
    'ACERO': { amarillo: 0.2, negro: 2, rojoNaranja: 0.1, blanco: 6 },
    'AZUL PROFUNDO': { negro: 0.35, blanco: 2.5, azul: 5.5, verde: 0.5 },
    'ADRA': { amarillo: 0.17, negro: 0.47, rojoNaranja: 0.07 },
    'SAMOS': { amarillo: 1.0, negro: 2.0, rojoNaranja: 0.63 },
    'PLOMO': { amarillo: 0.8, negro: 3.6, rojoNaranja: 1.3, blanco: 2.2 },
    'KALAHARI': { amarillo: 2, negro: 0.12, rojoNaranja: 0.33, blanco: 1.5 },
    'DESERT TAN': { amarillo: 1.8, negro: 0.5, rojoNaranja: 0.35, blanco: 1 },
    'COTTON': { amarillo: 0.6, negro: 0.15, rojoNaranja: 0.1, blanco: 30 },
    'NÉBULA': { amarillo: 0.17, negro: 0.04, blanco: 26 },
    'PERLA': { negro: 0.18 },
  },
  big: {
    'BLANCO': { blanco: 70 },
    'BLANCO ROTO': { amarillo: 0.18, negro: 0.08, rojoNaranja: 0.005, blanco: 36 },
    'BONE': { amarillo: 0.2, blanco: 7.4 },
    'SHALE GREY': { negro: 1.5, azul: 0.8 },
    'SPIKE': { rojoNaranja: 0.07, blanco: 4.83 },
    'LIQUEN': { amarillo: 0.06, negro: 0.13, blanco: 20, verde: 0.33 },
    'MOJAVE': { amarillo: 0.4, rojoNaranja: 0.08, blanco: 3.2 },
    'PORCELAIN': { blanco: 20, verde: 0.06, amarilloVainilla: 0.4, amarilloLimon: 0.4 },
    'UNIVERSE': { amarillo: 0.3, negro: 0.63, blanco: 10 },
    'MOSS': { blanco: 43.6, azul: 1.5, amarilloVainilla: 4.5 },
    'BREEZE': { amarillo: 0.25, blanco: 27.4, azul: 3.8, verde: 0.8 },
    'INDIA': { amarillo: 4.5, negro: 0.25, blanco: 48.0 },
    'BLUSH': { amarillo: 0.2, rojoIntenso: 0.05, blanco: 21.0, azul: 0.07 },
    'CORAL': { amarillo: 6.0, rojoNaranja: 11.0, blanco: 41.0 },
    'PAPYRUS': { amarillo: 0.95, negro: 1.33, blanco: 13 },
    'CHAMPAGNE': { amarillo: 2.1, negro: 0.4, blanco: 30 },
    'WASABI': { amarillo: 4.0, blanco: 29, verde: 2.5 },
    'KHAKI': { amarillo: 2.8, blanco: 20, verde: 2.0 },
    'SALMON': { amarillo: 4.0, negro: 0.1, rojoNaranja: 1.5, blanco: 32 },
    'CAFÉ': { amarillo: 6.6, negro: 2.1, rojoNaranja: 3.5, blanco: 27 },
    'SÁHARA': { amarillo: 2.9, negro: 0.3, rojoNaranja: 1.0, blanco: 45 },
    'JADE': { blanco: 10, azul: 6.0, amarilloVainilla: 15 },
    'CEMENTO': { negro: 0.6, blanco: 4.0, verde: 0.4 },
    'GINGER': { amarillo: 7.7, rojoNaranja: 0.1, blanco: 16 },
    'RAFFIA': { amarillo: 1.2, negro: 1, rojoNaranja: 0.2, blanco: 15 },
    'CAIRO': { amarillo: 0.15, negro: 0.04, rojoNaranja: 0.07, blanco: 0.8 },
    'CLAY': { amarillo: 2.3, negro: 0.18, rojoNaranja: 1.2, blanco: 15 },
    'MARRÓN': { amarillo: 0.4, negro: 1.6, rojoNaranja: 1 },
    'COBRE': { amarillo: 6.4, negro: 1, rojoNaranja: 4 },
    'SAND': { amarillo: 1.0, negro: 0.25, rojoNaranja: 0.06, blanco: 7 },
    'CALABAZA': { amarillo: 25, rojoNaranja: 10.0, blanco: 15 },
    'PINK': { amarillo: 0.25, rojoIntenso: 0.15, blanco: 17, azul: 0.1 },
    'EUCALYPTUS': { blanco: 24.0, azul: 1.8, amarilloVainilla: 10 },
    'HIMALAYA': { negro: 1.5, blanco: 3.0, azul: 0.07 },
    'PEARL GREY': { amarillo: 0.1, negro: 0.22, rojoNaranja: 0.03, blanco: 4.0 },
    'PIZARRA': { negro: 4 },
    'PURE BLACK': { negroHumo: 2.5 },
    'MOON': { amarillo: 0.7, negro: 5, blanco: 33 },
    'ACERO': { amarillo: 0.2, negro: 2, rojoNaranja: 0.1, blanco: 6 },
    'AZUL PROFUNDO': { negro: 0.35, blanco: 2.8 },
    'ADRA': { amarillo: 0.17, negro: 0.47, rojoNaranja: 0.07 },
    'SAMOS': { amarillo: 1, negro: 2.0, rojoNaranja: 0.6 },
    'PLOMO': { amarillo: 0.8, negro: 3.5, rojoNaranja: 1.3, blanco: 3 },
    'KALAHARI': { amarillo: 2.3, negro: 0.08, rojoNaranja: 0.33, blanco: 2.0 },
    'DESERT TAN': { amarillo: 1.8, negro: 0.5, rojoNaranja: 0.35, blanco: 1 },
    'COTTON': { amarillo: 0.6, negro: 0.15, rojoNaranja: 0.1, blanco: 30 },
    'NÉBULA': { amarillo: 0.17, negro: 0.04, blanco: 27 },
    'PERLA': { negro: 0.18, blanco: 11 },
  },
};
